# Generated by Django 4.0.2 on 2022-02-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
