# Generated by Django 4.0.2 on 2022-02-14 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_subtask_created_at_alter_subtask_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task'),
        ),
    ]
