# Generated by Django 4.0.2 on 2022-03-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_requestlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='staff_status',
            field=models.BooleanField(default=False),
        ),
    ]
